# XOR

-하나의 히든 레이어를 도입한다.

-input layer는 2개의 노드 + 1개의 바이어스

-hidden layer는 3개의 노드 + 1개의 바이어스

-output은 하나의 노드로 한다.

In [43]:
x = [[0,0,1],[1,0,1],[0,1,1],[1,1,1]] # 세번째 항은 bias
y = [0,1,1,0]

위의 데이터를 neural networks에서 backpropagation을 이용하여으로 학습시켜라.

In [44]:
import numpy as np
import math

In [45]:
def f(x):
    return 1/(1+np.exp(-x))

In [46]:
inp,hid,out=3,4,1

In [47]:
np.random.seed(1)
w=2*np.random.random((inp,hid))-1
om=2*np.random.random((hid,out))-1

In [48]:
o=[0,0,0,0]
k=0.1
se0=[0,0,0,0]
sej=[[0,0,0,0],[0,0,0,0],[0,0,0,0],[0,0,0,0]]

In [49]:
for i in range(4):
    neth=np.dot(x[i],w)
    h=f(neth)
    neto=np.dot(h,om)
    o[i]=f(neto)

In [50]:
o

[array([0.47372957]),
 array([0.54384086]),
 array([0.48895696]),
 array([0.54470837])]

In [55]:
for i in range(100):#반복 실행
    for i in range(4):
        se0[i]=(o[i]-y[i])*f(neto)*(1-f(neto))
        o[i]=o[i]-k*se0[i]*h[i]

    for i in range(4):
        for j in range(4):
            sej[i][j]=se0[i]*om[j]*f(neth[j])*(1-f(neth[j]))
        
    for i in range(4):
        for j in range(4):
            for v in range(3):
                w[v][j]=w[v][j]-k*sej[i][j]*x[i][v]

In [56]:
o

[array([0.07131048]),
 array([0.98118957]),
 array([0.82425177]),
 array([0.02402698])]